### ISSUE TITLE
missing error handling for private/non-existent repos

### ISSUE THREAD

**Issue by tobiasdam** [FH-CrOSSD/metrics#1]
Error when fetching private repo:

```python
Traceback (most recent call last):
  File "/home/tdam/fh/projects/crossd/metrics/src/crossd_metrics/main.py", line 34, in <module>
    Repository(owner="FH-CrOSSD", name="metrics")
  File "/home/tdam/fh/projects/crossd/metrics/src/crossd_metrics/Repository.py", line 340, in execute
    self.result = graph.result() | crawl.result() | rest.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/tdam/fh/projects/crossd/metrics/src/crossd_metrics/Repository.py", line 407, in _execute_crawl
    return self._execute_sequence(self.crawl)
  File "/home/tdam/fh/projects/crossd/metrics/src/crossd_metrics/Repository.py", line 413, in _execute_sequence
    rest_res = [elem() for elem in seq]
  File "/home/tdam/fh/projects/crossd/metrics/src/crossd_metrics/Repository.py", line 413, in <listcomp>
    rest_res = [elem() for elem in seq]
  File "/home/tdam/fh/projects/crossd/metrics/src/crossd_metrics/Repository.py", line 163, in _get_dependents
    urllib.request.urlopen(
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by tobiasdam** [comment]
This also results in:

```python
Traceback (most recent call last):
  File "/home/tdam/fh/projects/crossd/metrics/src/crossd_metrics/main.py", line 17, in <module>
    Repository(owner="10clouds", name="aiconsole")
  File "/home/tdam/fh/projects/crossd/metrics/src/crossd_metrics/Repository.py", line 335, in execute
    gres = graph.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/tdam/fh/projects/crossd/metrics/src/crossd_metrics/Request.py", line 40, in execute
    return client.execute(query)
  File "/home/tdam/fh/projects/crossd/metrics/.venv/lib/python3.10/site-packages/gql/client.py", line 403, in execute
    return self.execute_sync(
  File "/home/tdam/fh/projects/crossd/metrics/.venv/lib/python3.10/site-packages/gql/client.py", line 221, in execute_sync
    return session.execute(
  File "/home/tdam/fh/projects/crossd/metrics/.venv/lib/python3.10/site-packages/gql/client.py", line 860, in execute
    raise TransportQueryError(
gql.transport.exceptions.TransportQueryError: {'type': 'NOT_FOUND', 'path': ['repository'], 'locations': [{'line': 2, 'column': 3}], 'message': "Could not resolve to a Repository with the name '10clouds/aiconsole'."}
```
