### ISSUE TITLE
Error during crawling

### ISSUE THREAD

**Issue by tobiasdam** [FH-CrOSSD/metrics#2]
```python
2024-02-07 10:56:33,127: ERROR/ForkPoolWorker-1] Task retrieve_github[842f0880-f766-4b74-85bc-d53782545cc8] raised unexpected: AttributeError("'NoneType' object has no attribute 'get_text'")
Traceback (most recent call last):
  File "/home/collector-drone/.venv/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/collector-drone/.venv/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/collector-drone/src/drone/worker.py", line 134, in retrieve_github
    res = Repository(owner, name).ask_all().execute()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/pkgs/crossd_metrics/Repository.py", line 345, in execute
    self.result = graph.result() | crawl.result() | rest.result()
                                   ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/pkgs/crossd_metrics/Repository.py", line 412, in _execute_crawl
    return self._execute_sequence(self.crawl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/pkgs/crossd_metrics/Repository.py", line 418, in _execute_sequence
    rest_res = [elem() for elem in seq]
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/pkgs/crossd_metrics/Repository.py", line 418, in <listcomp>
    rest_res = [elem() for elem in seq]
                ^^^^^^
  File "/project/pkgs/crossd_metrics/Repository.py", line 173, in _get_dependents
    .get_text()
     ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_text'
```

**Comment by tobiasdam** [comment]
The error is not due to the project not having dependents. It's because the owner name changed and the selector tries to find old_owner/repo_name in it.
